{% set name = "xeus-sql" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-sql/archive/{{ version }}.tar.gz
  sha256: a56f8206290949eab3ed80257a8e308f06c4a2525126fe51119468c4fbce9016

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]
  host:
    # cpp-tabulate 1.5 is backward incompatible ...
    - cpp-tabulate >=1.5
    - nlohmann_json
    - soci-core
    - xeus-zmq >=3.0.0,<4
    - xproperty >=0.12,<0.13
    - xtl
    - xvega >=0.1.0
    - xvega-bindings >=0.1.0
  run:
    # xvega and xvega-bindings are missing run exports
    - {{ pin_compatible('xvega', max_pin='x.x') }}
    - {{ pin_compatible('xvega-bindings', max_pin='x.x') }}

test:
  commands:
    - test -f ${PREFIX}/bin/xsql  # [unix]
    - if exist %LIBRARY_PREFIX%\bin\xsql.exe (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/jupyter-xeus/xeus-xsql
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter kernel for SQL based on xeus and SOCI
  doc_url: https://xeus-sql.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - marimeireles
